Q:\Models\tools\ANY2G32.exe Kerrigan_inf_eye_D.tga        Kerrigan_inf_eye_D.g32       
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_eye_N.tga        Kerrigan_inf_eye_N.g32       
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_eye_S.tga        Kerrigan_inf_eye_S.g32       
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_head_D.tga       Kerrigan_inf_head_D.g32      
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_head_N.tga       Kerrigan_inf_head_N.g32      
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_head_S.tga       Kerrigan_inf_head_S.g32      
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_legswings_D.tga  Kerrigan_inf_legswings_D.g32 
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_legswings_N.tga  Kerrigan_inf_legswings_N.g32 
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_legswings_S.tga  Kerrigan_inf_legswings_S.g32 
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_torso_D.tga      Kerrigan_inf_torso_D.g32     
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_torso_N.tga      Kerrigan_inf_torso_N.g32     
Q:\Models\tools\ANY2G32.exe Kerrigan_inf_torso_S.tga      Kerrigan_inf_torso_S.g32     
